/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as PlanveoRouteImport } from './routes/planveo'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CitaRouteImport } from './routes/cita'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitaIndexRouteImport } from './routes/cita/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as TiendaSlugRouteImport } from './routes/tienda.$slug'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'
import { Route as CitaHorarioRouteImport } from './routes/cita/horario'
import { Route as CitaContactoRouteImport } from './routes/cita/contacto'
import { Route as CitaConfirmacionRouteImport } from './routes/cita/confirmacion'
import { Route as CitaCentroRouteImport } from './routes/cita/centro'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanveoRoute = PlanveoRouteImport.update({
  id: '/planveo',
  path: '/planveo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CitaRoute = CitaRouteImport.update({
  id: '/cita',
  path: '/cita',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitaIndexRoute = CitaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitaRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaSlugRoute = TiendaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TiendaRoute,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiciosRoute,
} as any)
const CitaHorarioRoute = CitaHorarioRouteImport.update({
  id: '/horario',
  path: '/horario',
  getParentRoute: () => CitaRoute,
} as any)
const CitaContactoRoute = CitaContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => CitaRoute,
} as any)
const CitaConfirmacionRoute = CitaConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => CitaRoute,
} as any)
const CitaCentroRoute = CitaCentroRouteImport.update({
  id: '/centro',
  path: '/centro',
  getParentRoute: () => CitaRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cita': typeof CitaRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/planveo': typeof PlanveoRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/tienda': typeof TiendaRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/cita/centro': typeof CitaCentroRoute
  '/cita/confirmacion': typeof CitaConfirmacionRoute
  '/cita/contacto': typeof CitaContactoRoute
  '/cita/horario': typeof CitaHorarioRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/cita/': typeof CitaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contacto': typeof ContactoRoute
  '/planveo': typeof PlanveoRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/tienda': typeof TiendaRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/cita/centro': typeof CitaCentroRoute
  '/cita/confirmacion': typeof CitaConfirmacionRoute
  '/cita/contacto': typeof CitaContactoRoute
  '/cita/horario': typeof CitaHorarioRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/blog': typeof BlogIndexRoute
  '/cita': typeof CitaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cita': typeof CitaRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/planveo': typeof PlanveoRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/tienda': typeof TiendaRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/cita/centro': typeof CitaCentroRoute
  '/cita/confirmacion': typeof CitaConfirmacionRoute
  '/cita/contacto': typeof CitaContactoRoute
  '/cita/horario': typeof CitaHorarioRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/cita/': typeof CitaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/cita'
    | '/contacto'
    | '/planveo'
    | '/quienes-somos'
    | '/servicios'
    | '/tienda'
    | '/blog/$slug'
    | '/cita/centro'
    | '/cita/confirmacion'
    | '/cita/contacto'
    | '/cita/horario'
    | '/servicios/$slug'
    | '/tienda/$slug'
    | '/blog/'
    | '/cita/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/contacto'
    | '/planveo'
    | '/quienes-somos'
    | '/servicios'
    | '/tienda'
    | '/blog/$slug'
    | '/cita/centro'
    | '/cita/confirmacion'
    | '/cita/contacto'
    | '/cita/horario'
    | '/servicios/$slug'
    | '/tienda/$slug'
    | '/blog'
    | '/cita'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/cita'
    | '/contacto'
    | '/planveo'
    | '/quienes-somos'
    | '/servicios'
    | '/tienda'
    | '/blog/$slug'
    | '/cita/centro'
    | '/cita/confirmacion'
    | '/cita/contacto'
    | '/cita/horario'
    | '/servicios/$slug'
    | '/tienda/$slug'
    | '/blog/'
    | '/cita/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CitaRoute: typeof CitaRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  PlanveoRoute: typeof PlanveoRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
  TiendaRoute: typeof TiendaRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planveo': {
      id: '/planveo'
      path: '/planveo'
      fullPath: '/planveo'
      preLoaderRoute: typeof PlanveoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cita': {
      id: '/cita'
      path: '/cita'
      fullPath: '/cita'
      preLoaderRoute: typeof CitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cita/': {
      id: '/cita/'
      path: '/'
      fullPath: '/cita/'
      preLoaderRoute: typeof CitaIndexRouteImport
      parentRoute: typeof CitaRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/$slug': {
      id: '/tienda/$slug'
      path: '/$slug'
      fullPath: '/tienda/$slug'
      preLoaderRoute: typeof TiendaSlugRouteImport
      parentRoute: typeof TiendaRoute
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/cita/horario': {
      id: '/cita/horario'
      path: '/horario'
      fullPath: '/cita/horario'
      preLoaderRoute: typeof CitaHorarioRouteImport
      parentRoute: typeof CitaRoute
    }
    '/cita/contacto': {
      id: '/cita/contacto'
      path: '/contacto'
      fullPath: '/cita/contacto'
      preLoaderRoute: typeof CitaContactoRouteImport
      parentRoute: typeof CitaRoute
    }
    '/cita/confirmacion': {
      id: '/cita/confirmacion'
      path: '/confirmacion'
      fullPath: '/cita/confirmacion'
      preLoaderRoute: typeof CitaConfirmacionRouteImport
      parentRoute: typeof CitaRoute
    }
    '/cita/centro': {
      id: '/cita/centro'
      path: '/centro'
      fullPath: '/cita/centro'
      preLoaderRoute: typeof CitaCentroRouteImport
      parentRoute: typeof CitaRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CitaRouteChildren {
  CitaCentroRoute: typeof CitaCentroRoute
  CitaConfirmacionRoute: typeof CitaConfirmacionRoute
  CitaContactoRoute: typeof CitaContactoRoute
  CitaHorarioRoute: typeof CitaHorarioRoute
  CitaIndexRoute: typeof CitaIndexRoute
}

const CitaRouteChildren: CitaRouteChildren = {
  CitaCentroRoute: CitaCentroRoute,
  CitaConfirmacionRoute: CitaConfirmacionRoute,
  CitaContactoRoute: CitaContactoRoute,
  CitaHorarioRoute: CitaHorarioRoute,
  CitaIndexRoute: CitaIndexRoute,
}

const CitaRouteWithChildren = CitaRoute._addFileChildren(CitaRouteChildren)

interface ServiciosRouteChildren {
  ServiciosSlugRoute: typeof ServiciosSlugRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosSlugRoute: ServiciosSlugRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

interface TiendaRouteChildren {
  TiendaSlugRoute: typeof TiendaSlugRoute
}

const TiendaRouteChildren: TiendaRouteChildren = {
  TiendaSlugRoute: TiendaSlugRoute,
}

const TiendaRouteWithChildren =
  TiendaRoute._addFileChildren(TiendaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CitaRoute: CitaRouteWithChildren,
  ContactoRoute: ContactoRoute,
  PlanveoRoute: PlanveoRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
  TiendaRoute: TiendaRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
