/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CitaRouteImport } from './routes/cita'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TiendaIndexRouteImport } from './routes/tienda/index'
import { Route as CitaIndexRouteImport } from './routes/cita/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as TiendaSlugRouteImport } from './routes/tienda/$slug'
import { Route as CitaHorarioRouteImport } from './routes/cita/horario'
import { Route as CitaContactoRouteImport } from './routes/cita/contacto'
import { Route as CitaConfirmacionRouteImport } from './routes/cita/confirmacion'
import { Route as CitaCentroRouteImport } from './routes/cita/centro'
import { Route as CheckoutResumenRouteImport } from './routes/checkout/resumen'
import { Route as CheckoutErrorRouteImport } from './routes/checkout/error'
import { Route as CheckoutEnvioRouteImport } from './routes/checkout/envio'
import { Route as CheckoutConfirmacionRouteImport } from './routes/checkout/confirmacion'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const CitaRoute = CitaRouteImport.update({
  id: '/cita',
  path: '/cita',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaIndexRoute = TiendaIndexRouteImport.update({
  id: '/tienda/',
  path: '/tienda/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitaIndexRoute = CitaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitaRoute,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaSlugRoute = TiendaSlugRouteImport.update({
  id: '/tienda/$slug',
  path: '/tienda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitaHorarioRoute = CitaHorarioRouteImport.update({
  id: '/horario',
  path: '/horario',
  getParentRoute: () => CitaRoute,
} as any)
const CitaContactoRoute = CitaContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => CitaRoute,
} as any)
const CitaConfirmacionRoute = CitaConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => CitaRoute,
} as any)
const CitaCentroRoute = CitaCentroRouteImport.update({
  id: '/centro',
  path: '/centro',
  getParentRoute: () => CitaRoute,
} as any)
const CheckoutResumenRoute = CheckoutResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutErrorRoute = CheckoutErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutEnvioRoute = CheckoutEnvioRouteImport.update({
  id: '/envio',
  path: '/envio',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutConfirmacionRoute = CheckoutConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => CheckoutRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/cita': typeof CitaRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/confirmacion': typeof CheckoutConfirmacionRoute
  '/checkout/envio': typeof CheckoutEnvioRoute
  '/checkout/error': typeof CheckoutErrorRoute
  '/checkout/resumen': typeof CheckoutResumenRoute
  '/cita/centro': typeof CitaCentroRoute
  '/cita/confirmacion': typeof CitaConfirmacionRoute
  '/cita/contacto': typeof CitaContactoRoute
  '/cita/horario': typeof CitaHorarioRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/cita/': typeof CitaIndexRoute
  '/tienda/': typeof TiendaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/carrito': typeof CarritoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/confirmacion': typeof CheckoutConfirmacionRoute
  '/checkout/envio': typeof CheckoutEnvioRoute
  '/checkout/error': typeof CheckoutErrorRoute
  '/checkout/resumen': typeof CheckoutResumenRoute
  '/cita/centro': typeof CitaCentroRoute
  '/cita/confirmacion': typeof CitaConfirmacionRoute
  '/cita/contacto': typeof CitaContactoRoute
  '/cita/horario': typeof CitaHorarioRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/blog': typeof BlogIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/cita': typeof CitaIndexRoute
  '/tienda': typeof TiendaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/cita': typeof CitaRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/confirmacion': typeof CheckoutConfirmacionRoute
  '/checkout/envio': typeof CheckoutEnvioRoute
  '/checkout/error': typeof CheckoutErrorRoute
  '/checkout/resumen': typeof CheckoutResumenRoute
  '/cita/centro': typeof CitaCentroRoute
  '/cita/confirmacion': typeof CitaConfirmacionRoute
  '/cita/contacto': typeof CitaContactoRoute
  '/cita/horario': typeof CitaHorarioRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/cita/': typeof CitaIndexRoute
  '/tienda/': typeof TiendaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/carrito'
    | '/checkout'
    | '/cita'
    | '/blog/$slug'
    | '/checkout/confirmacion'
    | '/checkout/envio'
    | '/checkout/error'
    | '/checkout/resumen'
    | '/cita/centro'
    | '/cita/confirmacion'
    | '/cita/contacto'
    | '/cita/horario'
    | '/tienda/$slug'
    | '/blog/'
    | '/checkout/'
    | '/cita/'
    | '/tienda/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/carrito'
    | '/blog/$slug'
    | '/checkout/confirmacion'
    | '/checkout/envio'
    | '/checkout/error'
    | '/checkout/resumen'
    | '/cita/centro'
    | '/cita/confirmacion'
    | '/cita/contacto'
    | '/cita/horario'
    | '/tienda/$slug'
    | '/blog'
    | '/checkout'
    | '/cita'
    | '/tienda'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/carrito'
    | '/checkout'
    | '/cita'
    | '/blog/$slug'
    | '/checkout/confirmacion'
    | '/checkout/envio'
    | '/checkout/error'
    | '/checkout/resumen'
    | '/cita/centro'
    | '/cita/confirmacion'
    | '/cita/contacto'
    | '/cita/horario'
    | '/tienda/$slug'
    | '/blog/'
    | '/checkout/'
    | '/cita/'
    | '/tienda/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CarritoRoute: typeof CarritoRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CitaRoute: typeof CitaRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  TiendaSlugRoute: typeof TiendaSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  TiendaIndexRoute: typeof TiendaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cita': {
      id: '/cita'
      path: '/cita'
      fullPath: '/cita'
      preLoaderRoute: typeof CitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/': {
      id: '/tienda/'
      path: '/tienda'
      fullPath: '/tienda/'
      preLoaderRoute: typeof TiendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cita/': {
      id: '/cita/'
      path: '/'
      fullPath: '/cita/'
      preLoaderRoute: typeof CitaIndexRouteImport
      parentRoute: typeof CitaRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/$slug': {
      id: '/tienda/$slug'
      path: '/tienda/$slug'
      fullPath: '/tienda/$slug'
      preLoaderRoute: typeof TiendaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cita/horario': {
      id: '/cita/horario'
      path: '/horario'
      fullPath: '/cita/horario'
      preLoaderRoute: typeof CitaHorarioRouteImport
      parentRoute: typeof CitaRoute
    }
    '/cita/contacto': {
      id: '/cita/contacto'
      path: '/contacto'
      fullPath: '/cita/contacto'
      preLoaderRoute: typeof CitaContactoRouteImport
      parentRoute: typeof CitaRoute
    }
    '/cita/confirmacion': {
      id: '/cita/confirmacion'
      path: '/confirmacion'
      fullPath: '/cita/confirmacion'
      preLoaderRoute: typeof CitaConfirmacionRouteImport
      parentRoute: typeof CitaRoute
    }
    '/cita/centro': {
      id: '/cita/centro'
      path: '/centro'
      fullPath: '/cita/centro'
      preLoaderRoute: typeof CitaCentroRouteImport
      parentRoute: typeof CitaRoute
    }
    '/checkout/resumen': {
      id: '/checkout/resumen'
      path: '/resumen'
      fullPath: '/checkout/resumen'
      preLoaderRoute: typeof CheckoutResumenRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/error': {
      id: '/checkout/error'
      path: '/error'
      fullPath: '/checkout/error'
      preLoaderRoute: typeof CheckoutErrorRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/envio': {
      id: '/checkout/envio'
      path: '/envio'
      fullPath: '/checkout/envio'
      preLoaderRoute: typeof CheckoutEnvioRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/confirmacion': {
      id: '/checkout/confirmacion'
      path: '/confirmacion'
      fullPath: '/checkout/confirmacion'
      preLoaderRoute: typeof CheckoutConfirmacionRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutConfirmacionRoute: typeof CheckoutConfirmacionRoute
  CheckoutEnvioRoute: typeof CheckoutEnvioRoute
  CheckoutErrorRoute: typeof CheckoutErrorRoute
  CheckoutResumenRoute: typeof CheckoutResumenRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutConfirmacionRoute: CheckoutConfirmacionRoute,
  CheckoutEnvioRoute: CheckoutEnvioRoute,
  CheckoutErrorRoute: CheckoutErrorRoute,
  CheckoutResumenRoute: CheckoutResumenRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface CitaRouteChildren {
  CitaCentroRoute: typeof CitaCentroRoute
  CitaConfirmacionRoute: typeof CitaConfirmacionRoute
  CitaContactoRoute: typeof CitaContactoRoute
  CitaHorarioRoute: typeof CitaHorarioRoute
  CitaIndexRoute: typeof CitaIndexRoute
}

const CitaRouteChildren: CitaRouteChildren = {
  CitaCentroRoute: CitaCentroRoute,
  CitaConfirmacionRoute: CitaConfirmacionRoute,
  CitaContactoRoute: CitaContactoRoute,
  CitaHorarioRoute: CitaHorarioRoute,
  CitaIndexRoute: CitaIndexRoute,
}

const CitaRouteWithChildren = CitaRoute._addFileChildren(CitaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CarritoRoute: CarritoRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CitaRoute: CitaRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  TiendaSlugRoute: TiendaSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  TiendaIndexRoute: TiendaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
