name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    name: ${{ matrix.check-name }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - check-name: 'TypeScript Check'
            command: 'npm run typecheck'
          - check-name: 'ESLint Check'
            command: 'npm run lint'
          - check-name: 'Prettier Check'
            command: 'npm run format'
          - check-name: 'Build Check'
            command: 'npm run build'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run check
        run: ${{ matrix.command }}

  e2e-tests:
    runs-on: ubuntu-latest
    name: E2E Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build application
        run: npm run build

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
